-- =====================================================================
-- Café Faim — seed content
-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Run after schema.sql. Re-running replaces all content with this file,
-- so do NOT re-run once the owner has started editing in the dashboard.
-- =====================================================================

begin;

-- Wipe first so the seed is repeatable. Cascades clear sections + items.
delete from public.menu_items;
delete from public.menu_sections;
delete from public.menu_cards;
delete from public.gallery_photos;
delete from public.cakes;
delete from public.concept_pills;
delete from public.concept;

-- ---------- concept ----------
insert into public.concept (id, kicker_nl, kicker_en, heading_nl, heading_en, body1_nl, body1_en, body2_nl, body2_en) values
  (1, 'Het concept', 'The concept', 'Een plek waar je blijft hangen', 'A place where you linger', 'Café Faim is een plek waar je samenkomt, waar je blijft hangen, waar je even ontsnapt aan de drukte en gewoon geniet. Een kleine pauze in je dag — met de geur van vers gebakken lekkers om je heen.', 'Café Faim is a place where you come together, where you linger, where you escape the rush for a moment and simply enjoy. A small pause in your day — surrounded by the smell of freshly baked treats.', 'Alles wat je hier proeft wordt met liefde en aandacht gemaakt. Denk aan loaded cookies die rijk gevuld zijn en precies goed in elke bite, romige cheesecakes, gepersonaliseerde taarten en speelse cakepops die eruitzien als kleine cadeautjes.', 'Everything you taste here is made with love and attention. Think loaded cookies that are richly filled and just right in every bite, creamy cheesecakes, personalised cakes and playful cakepops that look like little gifts.');

insert into public.concept_pills (id, position, strong_nl, strong_en, label_nl, label_en) values
  ('00000000-0000-4000-8000-000000000001', 0, '100%', null, 'Halal', 'Halal'),
  ('00000000-0000-4000-8000-000000000002', 1, 'Vers', 'Fresh', 'Elke dag', 'Every day'),
  ('00000000-0000-4000-8000-000000000003', 2, 'Matcha', null, 'Huisfavoriet', 'House favourite'),
  ('00000000-0000-4000-8000-000000000004', 3, 'Op maat', 'Custom', 'Taarten', 'Cakes');

-- ---------- custom cakes ----------
insert into public.cakes (id, position, image_path, alt, title_nl, title_en, blurb_nl, blurb_en) values
  ('00000000-0000-4000-8000-000000000005', 0, 'assets/gallery/verjaardag-goud.jpg', 'Roze verjaardagstaart met gouden drip en macarons', 'Verjaardagstaarten', 'Birthday cakes', 'Van klassiek tot volledig custom.', 'From classic to fully custom.'),
  ('00000000-0000-4000-8000-000000000006', 1, 'assets/gallery/bruiloft-ruffle.jpg', 'Tweelaagse bruiloftstaart met ruffles en gipskruid', 'Bruiloftstaarten', 'Wedding cakes', 'Meerdere lagen, bloemen, jouw stijl.', 'Multi-tier, florals, your style.'),
  ('00000000-0000-4000-8000-000000000007', 2, 'assets/gallery/babyshower-vlinder.jpg', 'Roze babyshowertaart met gouden silhouet en vlinders', 'Babyshower & gender reveal', 'Baby shower & gender reveal', 'Zacht, lief en persoonlijk.', 'Soft, sweet and personal.'),
  ('00000000-0000-4000-8000-000000000008', 3, 'assets/gallery/sweettable-box.jpg', 'Sweet table box met cakesicles, cupcakes en gouden details', 'Sweet tables', 'Sweet tables', 'Cakesicles, cupcakes en desserts voor je feest.', 'Cakesicles, cupcakes and desserts for your party.');

-- ---------- gallery ----------
insert into public.gallery_photos (id, position, image_path, alt, caption_nl, caption_en) values
  ('00000000-0000-4000-8000-000000000009', 0, 'assets/gallery/bruiloft-ruffle.jpg', 'Tweelaagse bruiloftstaart met ruffles en gipskruid', 'Bruiloftstaarten', 'Wedding cakes'),
  ('00000000-0000-4000-8000-000000000010', 1, 'assets/gallery/babyshower-vlinder.jpg', 'Roze babyshowertaart met gouden silhouet en vlinders', 'Babyshower', 'Baby shower'),
  ('00000000-0000-4000-8000-000000000011', 2, 'assets/gallery/verjaardag-goud.jpg', 'Roze verjaardagstaart met gouden drip en macarons', 'Verjaardagstaarten', 'Birthday cakes'),
  ('00000000-0000-4000-8000-000000000012', 3, 'assets/gallery/sweettable-box.jpg', 'Sweet table box met cakesicles, cupcakes en gouden details', 'Sweet tables', 'Sweet tables'),
  ('00000000-0000-4000-8000-000000000013', 4, 'assets/gallery/ohbaby-drip.jpg', 'Roze ''Oh Baby'' taart met witte chocoladedrip', 'Oh Baby', 'Oh Baby'),
  ('00000000-0000-4000-8000-000000000014', 5, 'assets/gallery/kinder-pikachu.jpg', 'Kindertaart met Pikachu en gele botercrème', 'Kindertaarten', 'Kids'' cakes'),
  ('00000000-0000-4000-8000-000000000015', 6, 'assets/gallery/bridetobe-anjers.jpg', 'Bride to be taart met anjers en witte ruffles', 'Bride to be', 'Bride to be'),
  ('00000000-0000-4000-8000-000000000016', 7, 'assets/gallery/henna-rozen.jpg', 'Witte hennataart met rode en witte rozen', 'Henna & bruiloft', 'Henna & wedding');

-- ---------- menu ----------
insert into public.menu_cards (id, position, title_nl, title_en) values
  ('00000000-0000-4000-8000-000000000017', 0, 'Lunch', null),
  ('00000000-0000-4000-8000-000000000044', 1, 'Dranken', 'Drinks');

insert into public.menu_sections (id, card_id, parent_id, column_index, position, kind, sub,
  heading_nl, heading_en, lead_nl, lead_en, note_nl, note_en, badge_nl, badge_en, text_nl, text_en) values
  ('00000000-0000-4000-8000-000000000018', '00000000-0000-4000-8000-000000000017', null, 0, 0, 'group', false, 'Broodjes', 'Sandwiches', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000024', '00000000-0000-4000-8000-000000000017', null, 0, 1, 'group', false, 'Salades', 'Salads', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000028', '00000000-0000-4000-8000-000000000017', null, 1, 0, 'group', false, 'Pannenkoeken', 'Pancakes', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000032', '00000000-0000-4000-8000-000000000017', null, 1, 1, 'boxList', false, 'Gebak', 'Pastries', 'Dagelijkse selectie aan de toonbank', 'Daily selection at the counter', 'Aanbod kan dagelijks variëren.', 'Selection may vary daily.', null, null, null, null),
  ('00000000-0000-4000-8000-000000000043', '00000000-0000-4000-8000-000000000017', null, 1, 2, 'till', false, null, null, null, null, null, null, null, null, 'Lunch tot 15:00', 'Lunch till 15:00'),
  ('00000000-0000-4000-8000-000000000045', '00000000-0000-4000-8000-000000000044', null, 0, 0, 'group', false, 'Warme Dranken', 'Hot Drinks', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000053', '00000000-0000-4000-8000-000000000044', null, 0, 1, 'group', false, 'IJskoffie', 'Iced Coffee', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000060', '00000000-0000-4000-8000-000000000044', null, 0, 2, 'box', false, 'Extra''s', 'Extras', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000065', '00000000-0000-4000-8000-000000000044', null, 1, 0, 'feature', false, null, null, null, null, null, null, 'Huisfavoriet', 'House favourite', null, null),
  ('00000000-0000-4000-8000-000000000066', null, '00000000-0000-4000-8000-000000000065', 0, 0, 'group', false, 'Matcha', null, null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000068', null, '00000000-0000-4000-8000-000000000065', 0, 1, 'group', true, 'Specials', 'Specialty', null, null, null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000072', '00000000-0000-4000-8000-000000000044', null, 1, 1, 'group', false, 'Frisdranken', 'Beverages', null, null, null, null, null, null, null, null);

insert into public.menu_items (id, section_id, position, name_nl, name_en, price, desc_nl, desc_en, from_nl, from_en) values
  ('00000000-0000-4000-8000-000000000019', '00000000-0000-4000-8000-000000000018', 0, 'Carpaccio', null, '€11.95', 'Focaccia, rucola, Parmezaanse kaas, pijnboompitten, truffelmayonaise', 'Focaccia bread, Rucola, Parmesan cheese, Pine nuts, Truffle mayo', null, null),
  ('00000000-0000-4000-8000-000000000020', '00000000-0000-4000-8000-000000000018', 1, 'Caprese', null, '€8.95', 'Focaccia, mozzarella, tomaat, huisgemaakte groene pesto, rucola', 'Focaccia bread, Mozzarella, Tomato, Homemade green pesto, Rucola', null, null),
  ('00000000-0000-4000-8000-000000000021', '00000000-0000-4000-8000-000000000018', 2, 'Tonijn Melt', 'Tuna Melt', '€9.95', 'Focaccia, tonijnsalade, kaas, cherrytomaat, rode ui, sla', 'Focaccia bread, Tuna salad, Cheese, Cherrytomato, Red onion, Lettuce', null, null),
  ('00000000-0000-4000-8000-000000000022', '00000000-0000-4000-8000-000000000018', 3, 'Gerookte Zalm', 'Smoked Salmon', '€12.95', 'Focaccia, avocado, roomkaas, dille, citroendressing, rucola', 'Focaccia bread, Avocado, Cream cheese, Dill, Lemon dressing, Rucola', null, null),
  ('00000000-0000-4000-8000-000000000023', '00000000-0000-4000-8000-000000000018', 4, 'Hete Kip', 'Spicy Chicken', '€10.95', 'Focaccia, sla, kip, kaas, speciale Faim-saus', 'Focaccia bread, Lettuce, Chicken, Cheese, Special Faim sauce', null, null),
  ('00000000-0000-4000-8000-000000000025', '00000000-0000-4000-8000-000000000024', 0, 'Burrata', null, '€14.95', 'Burrata, komkommer, vijgen, gerookte amandelen, tomaat, balsamicostroop, huisgemaakte groene pesto', 'Burrata, Cucumber, Figs, Smoked almonds, Tomato, Balsamic glaze, Homemade green pesto', null, null),
  ('00000000-0000-4000-8000-000000000026', '00000000-0000-4000-8000-000000000024', 1, 'Caesar', 'Ceasar', '€13.95', 'Romaine sla, Parmezaanse kaas, croutons, gekookt ei, kip en Caesardressing', 'Romaine lettuce, Parmesan cheese, Croutons, Boiled egg, Chicken and Ceaser dressing', null, null),
  ('00000000-0000-4000-8000-000000000027', '00000000-0000-4000-8000-000000000024', 2, 'Zalm', 'Salmon', '€14.95', 'Romaine sla, kappertjes, rode ui, tomaat, komkommer en honing-mosterd-dilledressing', 'Romaine lettuce, Capers, Red onion, Tomato, Cucumber and Honey mustard dill dressing', null, null),
  ('00000000-0000-4000-8000-000000000029', '00000000-0000-4000-8000-000000000028', 0, 'Choco Banaan Amandel', 'Choco Ban Almo', '€9.95', 'Amandelmascarpone, amandelpraliné, banaan, amandelen, chocoladestukjes en ahornsiroop', 'Almond mascarpone, Almond praline, Bananas, Almonds, Chocolate chips and Maple syrup', null, null),
  ('00000000-0000-4000-8000-000000000030', '00000000-0000-4000-8000-000000000028', 1, 'Pistache Rode Vruchten', 'Pistachio Berries', '€10.95', 'Pistachemascarpone, pistachepraliné, rode vruchten, pistachenoten, rozenblaadjes en ahornsiroop', 'Pistachio mascarpone, Pistachio praline, Red fruits, Pistachios, Rose petals and Maple syrup', null, null),
  ('00000000-0000-4000-8000-000000000031', '00000000-0000-4000-8000-000000000028', 2, 'Loaded Biscoff', null, '€9.95', 'Biscoff mascarpone, Lotus crumble, Biscoff en witte chocoladepasta', 'Biscoff mascarpone, Lotus crumbles, Biscoff and White chocolate spread', null, null),
  ('00000000-0000-4000-8000-000000000033', '00000000-0000-4000-8000-000000000032', 0, 'Koekjes', 'Cookies', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000034', '00000000-0000-4000-8000-000000000032', 1, 'Taartpunten', 'Cake slices', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000035', '00000000-0000-4000-8000-000000000032', 2, 'Kaneelbroodjes', 'Cinnamon rolls', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000036', '00000000-0000-4000-8000-000000000032', 3, 'Cheesecake', null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000037', '00000000-0000-4000-8000-000000000032', 4, 'Tiramisu', null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000038', '00000000-0000-4000-8000-000000000032', 5, 'Brownies', null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000039', '00000000-0000-4000-8000-000000000032', 6, 'Muffins', null, null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000040', '00000000-0000-4000-8000-000000000032', 7, 'Dessertbekers', 'Dessert cups', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000041', '00000000-0000-4000-8000-000000000032', 8, 'Signature gebak', 'Signature pastries', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000042', '00000000-0000-4000-8000-000000000032', 9, 'Bananenbrood', 'Banana bread', null, null, null, null, null),
  ('00000000-0000-4000-8000-000000000046', '00000000-0000-4000-8000-000000000045', 0, 'Koffie', 'Coffee', '€3.20', null, null, null, null),
  ('00000000-0000-4000-8000-000000000047', '00000000-0000-4000-8000-000000000045', 1, 'Espresso', null, '€3.20', null, null, null, null),
  ('00000000-0000-4000-8000-000000000048', '00000000-0000-4000-8000-000000000045', 2, 'Cappuccino', null, '€3.40', null, null, null, null),
  ('00000000-0000-4000-8000-000000000049', '00000000-0000-4000-8000-000000000045', 3, 'Macchiato', null, '€4.10', null, null, null, null),
  ('00000000-0000-4000-8000-000000000050', '00000000-0000-4000-8000-000000000045', 4, 'Flat White', null, '€4.90', null, null, null, null),
  ('00000000-0000-4000-8000-000000000051', '00000000-0000-4000-8000-000000000045', 5, 'Warme Chocolademelk', 'Hot Chocolate', '€3.70', null, null, null, null),
  ('00000000-0000-4000-8000-000000000052', '00000000-0000-4000-8000-000000000045', 6, 'Thee', 'Tea', '€3.40', null, null, null, null),
  ('00000000-0000-4000-8000-000000000054', '00000000-0000-4000-8000-000000000053', 0, 'Klassiek', 'Classic', '€5.50', null, null, null, null),
  ('00000000-0000-4000-8000-000000000055', '00000000-0000-4000-8000-000000000053', 1, 'Karamel', 'Caramel', '€5.70', null, null, null, null),
  ('00000000-0000-4000-8000-000000000056', '00000000-0000-4000-8000-000000000053', 2, 'Vanille', 'Vanilla', '€5.70', null, null, null, null),
  ('00000000-0000-4000-8000-000000000057', '00000000-0000-4000-8000-000000000053', 3, 'Chocolade', 'Chocolate', '€5.70', null, null, null, null),
  ('00000000-0000-4000-8000-000000000058', '00000000-0000-4000-8000-000000000053', 4, 'Crème Brûlée', null, '€6.50', null, null, null, null),
  ('00000000-0000-4000-8000-000000000059', '00000000-0000-4000-8000-000000000053', 5, 'Tiramisu', null, '€6.50', null, null, null, null),
  ('00000000-0000-4000-8000-000000000061', '00000000-0000-4000-8000-000000000060', 0, 'Slagroom', 'Whipped Cream', '€0.50', null, null, null, null),
  ('00000000-0000-4000-8000-000000000062', '00000000-0000-4000-8000-000000000060', 1, 'Cold Foam', null, '€0.75', null, null, null, null),
  ('00000000-0000-4000-8000-000000000063', '00000000-0000-4000-8000-000000000060', 2, 'Siroop', 'Syrup', '€0.75', null, null, null, null),
  ('00000000-0000-4000-8000-000000000064', '00000000-0000-4000-8000-000000000060', 3, 'Melkopties', 'Milk Options', '€0.50', null, null, null, null),
  ('00000000-0000-4000-8000-000000000067', '00000000-0000-4000-8000-000000000066', 0, 'Iced Latte', null, '€7.00', 'Kies smaak, melk en siroop naar wens — vraag de barista naar de opties.', 'Choose your flavor, milk and syrup — ask the barista for the options.', 'Vanaf', 'From'),
  ('00000000-0000-4000-8000-000000000069', '00000000-0000-4000-8000-000000000068', 0, 'Strawberry Shortcake', null, '€8.00', 'Aardbei, koekjessiroop, melk naar keuze, aardbeien cold foam, koekjeskruimels', 'Strawberry, Cookie syrup, Milk of choice, Strawberry cold foam, Cookie crumbs', null, null),
  ('00000000-0000-4000-8000-000000000070', '00000000-0000-4000-8000-000000000068', 1, 'Crème Brûlée', null, '€8.00', 'Vanillesiroop, melk naar keuze, matcha, crème brûlée met gekarameliseerde suiker', 'Vanilla syrup, Milk of choice, Matcha, Crème brûlée with caramelized sugar', null, null),
  ('00000000-0000-4000-8000-000000000071', '00000000-0000-4000-8000-000000000068', 2, 'Coconut Cloud', null, '€7.75', 'Kokoswater, romige matcha', 'Coconut water, Creamy matcha', null, null),
  ('00000000-0000-4000-8000-000000000073', '00000000-0000-4000-8000-000000000072', 0, 'Coca Cola', null, '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000074', '00000000-0000-4000-8000-000000000072', 1, 'Cola Zero', null, '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000075', '00000000-0000-4000-8000-000000000072', 2, 'Fanta', null, '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000076', '00000000-0000-4000-8000-000000000072', 3, 'Sprite', null, '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000077', '00000000-0000-4000-8000-000000000072', 4, 'Ice Tea', null, '€3.40', null, null, null, null),
  ('00000000-0000-4000-8000-000000000078', '00000000-0000-4000-8000-000000000072', 5, 'Ice Tea Perzik', 'Ice Tea Peach', '€3.40', null, null, null, null),
  ('00000000-0000-4000-8000-000000000079', '00000000-0000-4000-8000-000000000072', 6, 'Appelsap', 'Apple Juice', '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000080', '00000000-0000-4000-8000-000000000072', 7, 'Sinaasappelsap', 'Orange Juice', '€3.30', null, null, null, null),
  ('00000000-0000-4000-8000-000000000081', '00000000-0000-4000-8000-000000000072', 8, 'Water / Bruisend', 'Water / Sparkling', '€2.90', null, null, null, null),
  ('00000000-0000-4000-8000-000000000082', '00000000-0000-4000-8000-000000000072', 9, 'Red Bull', null, '€3.90', null, null, null, null);

commit;
