/*
 * Writes supabase/seed.sql from the bundled content in src/data.
 *
 * Generating the seed instead of hand-writing it means the database starts as
 * an exact copy of the site as it ships, and the same files keep serving as the
 * offline fallback. Re-run with `npm run seed:generate` after editing src/data.
 *
 * IDs are deterministic (a counter, not random) so re-running produces an
 * identical file and git shows a clean diff.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { lunchCard, drinksCard } from '../src/data/menu.js';
import { cakeCategories, galleryPhotos } from '../src/data/gallery.js';
import { conceptBlock, conceptPills } from '../src/data/concept.js';

let counter = 0;
const uid = () => {
  counter += 1;
  return `00000000-0000-4000-8000-${String(counter).padStart(12, '0')}`;
};

// SQL literal. Doubling the quote is the escape; null stays unquoted.
const q = (v) => (v === undefined || v === null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`);

// A field is either a { nl, en } pair or a bare string meaning "same in both".
// Bare strings write only _nl and leave _en null, which is exactly what the
// admin UI shows as an empty English box and what t() falls back on.
const pair = (v) => {
  if (v === undefined || v === null) return [null, null];
  if (typeof v === 'object') return [v.nl ?? null, v.en ?? null];
  return [v, null];
};
const pairSql = (v) => pair(v).map(q).join(', ');

const out = [];
const w = (line = '') => out.push(line);

w('-- =====================================================================');
w('-- Café Faim — seed content');
w('-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.');
w('-- Run after schema.sql. Re-running replaces all content with this file,');
w('-- so do NOT re-run once the owner has started editing in the dashboard.');
w('-- =====================================================================');
w();
w('begin;');
w();
w('-- Wipe first so the seed is repeatable. Cascades clear sections + items.');
w('delete from public.menu_items;');
w('delete from public.menu_sections;');
w('delete from public.menu_cards;');
w('delete from public.gallery_photos;');
w('delete from public.cakes;');
w('delete from public.concept_pills;');
w('delete from public.concept;');
w();

// ---- concept -------------------------------------------------------------
w('-- ---------- concept ----------');
w('insert into public.concept (id, kicker_nl, kicker_en, heading_nl, heading_en, body1_nl, body1_en, body2_nl, body2_en) values');
w(
  `  (1, ${pairSql(conceptBlock.kicker)}, ${pairSql(conceptBlock.heading)}, ` +
    `${pairSql(conceptBlock.body1)}, ${pairSql(conceptBlock.body2)});`
);
w();

w('insert into public.concept_pills (id, position, strong_nl, strong_en, label_nl, label_en) values');
w(
  conceptPills
    .map((p, i) => `  (${q(uid())}, ${i}, ${pairSql(p.strong)}, ${pairSql(p.label)})`)
    .join(',\n') + ';'
);
w();

// ---- cakes ---------------------------------------------------------------
w('-- ---------- custom cakes ----------');
w('insert into public.cakes (id, position, image_path, alt, title_nl, title_en, blurb_nl, blurb_en) values');
w(
  cakeCategories
    .map(
      (c, i) =>
        `  (${q(uid())}, ${i}, ${q(c.src)}, ${q(c.alt)}, ${pairSql(c.title)}, ${pairSql(c.blurb)})`
    )
    .join(',\n') + ';'
);
w();

// ---- gallery -------------------------------------------------------------
w('-- ---------- gallery ----------');
w('insert into public.gallery_photos (id, position, image_path, alt, caption_nl, caption_en) values');
w(
  galleryPhotos
    .map((p, i) => `  (${q(uid())}, ${i}, ${q(p.src)}, ${q(p.alt)}, ${pairSql(p.caption)})`)
    .join(',\n') + ';'
);
w();

// ---- menu ----------------------------------------------------------------
w('-- ---------- menu ----------');

const cardRows = [];
const sectionRows = [];
const itemRows = [];

const addItems = (sectionId, items = []) => {
  items.forEach((item, i) => {
    itemRows.push(
      `  (${q(uid())}, ${q(sectionId)}, ${i}, ${pairSql(item.name)}, ${q(item.price)}, ` +
        `${pairSql(item.desc)}, ${pairSql(item.from)})`
    );
  });
};

const addSection = (section, { cardId, parentId, columnIndex, position }) => {
  const id = uid();
  sectionRows.push(
    `  (${q(id)}, ${q(cardId)}, ${q(parentId)}, ${columnIndex}, ${position}, ` +
      `${q(section.kind ?? 'group')}, ${section.sub ? 'true' : 'false'}, ` +
      `${pairSql(section.heading)}, ${pairSql(section.lead)}, ${pairSql(section.note)}, ` +
      `${pairSql(section.badge)}, ${pairSql(section.text)})`
  );

  if (section.kind === 'feature') {
    // The feature panel's groups become child sections of the panel itself.
    (section.groups ?? []).forEach((group, gi) =>
      addSection({ ...group, kind: 'group' }, {
        cardId: null,
        parentId: id,
        columnIndex: 0,
        position: gi,
      })
    );
  } else if (section.kind === 'boxList') {
    // The unpriced "Gebak" names are stored as ordinary items without a price,
    // so one editor screen covers every list on the menu.
    (section.list ?? []).forEach((entry, i) => {
      itemRows.push(
        `  (${q(uid())}, ${q(id)}, ${i}, ${pairSql(entry)}, null, null, null, null, null)`
      );
    });
  } else {
    addItems(id, section.items);
  }
};

[lunchCard, drinksCard].forEach((card, cardIndex) => {
  const cardId = uid();
  cardRows.push(`  (${q(cardId)}, ${cardIndex}, ${pairSql(card.title)})`);
  card.columns.forEach((column, columnIndex) => {
    column.forEach((section, position) =>
      addSection(section, { cardId, parentId: null, columnIndex, position })
    );
  });
});

w('insert into public.menu_cards (id, position, title_nl, title_en) values');
w(cardRows.join(',\n') + ';');
w();
w('insert into public.menu_sections (id, card_id, parent_id, column_index, position, kind, sub,');
w('  heading_nl, heading_en, lead_nl, lead_en, note_nl, note_en, badge_nl, badge_en, text_nl, text_en) values');
w(sectionRows.join(',\n') + ';');
w();
w('insert into public.menu_items (id, section_id, position, name_nl, name_en, price, desc_nl, desc_en, from_nl, from_en) values');
w(itemRows.join(',\n') + ';');
w();
w('commit;');
w();

mkdirSync('supabase', { recursive: true });
writeFileSync('supabase/seed.sql', out.join('\n'), 'utf8');
console.log(
  `seed.sql written — ${cardRows.length} cards, ${sectionRows.length} sections, ${itemRows.length} items, ` +
    `${cakeCategories.length} cakes, ${galleryPhotos.length} photos`
);
